apiVersion: apps/v1
kind: Deployment
metadata:
  name: pal-tracker
  labels:
    app: pal-tracker
spec:
  selector:
    matchLabels:
      app: pal-tracker
      name: pal-tracker-pod
  template:
    # Pod definition starts here
    metadata:
      labels:
        app: pal-tracker
        name: pal-tracker-pod
    spec:
      containers:
        - name: pal-tracker-container
          image: steveelliottvmware/pal-tracker:v3
          envFrom:
            - secretRef:
                name: db-credentials
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 150
          lifecycle:
            preStop:
              exec:
                command: [ "/bin/sleep", "10" ]
          env:
            - name: WELCOME_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: pal-tracker
                  key: welcome.message
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              valueFrom:
                configMapKeyRef:
                  name: pal-tracker
                  key: management.endpoints.web.exposure.include
            - name: SPRING_DATASOURCE_HIKARI_MAXIMUMPOOLSIZE
              valueFrom:
                configMapKeyRef:
                  name: pal-tracker
                  key: spring.datasource.hikari.maximumpoolsize
